[options]
library = "Vte"
version = "2.91"
target_path = "."
work_mode = "sys"
girs_directories = ["../gir-files/"]

external_libraries = [
    "Gtk",
    "GLib",
    "Gio",
    "Gdk",
    "Pango",
]
