// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir-files
// DO NOT EDIT

mod pty;
pub use self::pty::Pty;

mod terminal;
pub use self::terminal::{Terminal, NONE_TERMINAL};

mod regex;
pub use self::regex::Regex;

mod enums;
pub use self::enums::CursorBlinkMode;
pub use self::enums::CursorShape;
pub use self::enums::EraseBinding;
#[cfg(any(feature = "v0_50", feature = "dox"))]
#[cfg_attr(feature = "dox", doc(cfg(feature = "v0_50")))]
pub use self::enums::Format;
pub use self::enums::PtyError;
#[cfg(any(feature = "v0_52", feature = "dox"))]
#[cfg_attr(feature = "dox", doc(cfg(feature = "v0_52")))]
pub use self::enums::TextBlinkMode;
pub use self::enums::WriteFlags;

mod flags;
pub use self::flags::PtyFlags;

#[doc(hidden)]
pub mod traits {
    pub use super::terminal::TerminalExt;
}
