// Generated by gir (https://github.com/gtk-rs/gir @ e8f82cf6)
// from ../gir-files (@ 8e47c67)
// DO NOT EDIT

#include "manual.h"
#include <stdio.h>

#define PRINT_CONSTANT(CONSTANT_NAME) \
    printf("%s;", #CONSTANT_NAME); \
    printf(_Generic((CONSTANT_NAME), \
                    char *: "%s", \
                    const char *: "%s", \
                    char: "%c", \
                    signed char: "%hhd", \
                    unsigned char: "%hhu", \
                    short int: "%hd", \
                    unsigned short int: "%hu", \
                    int: "%d", \
                    unsigned int: "%u", \
                    long: "%ld", \
                    unsigned long: "%lu", \
                    long long: "%lld", \
                    unsigned long long: "%llu", \
                    float: "%f", \
                    double: "%f", \
                    long double: "%ld"), \
           CONSTANT_NAME); \
    printf("\n");

int main() {
    PRINT_CONSTANT((gint) VTE_CURSOR_BLINK_OFF);
    PRINT_CONSTANT((gint) VTE_CURSOR_BLINK_ON);
    PRINT_CONSTANT((gint) VTE_CURSOR_BLINK_SYSTEM);
    PRINT_CONSTANT((gint) VTE_CURSOR_SHAPE_BLOCK);
    PRINT_CONSTANT((gint) VTE_CURSOR_SHAPE_IBEAM);
    PRINT_CONSTANT((gint) VTE_CURSOR_SHAPE_UNDERLINE);
    PRINT_CONSTANT((gint) VTE_ERASE_ASCII_BACKSPACE);
    PRINT_CONSTANT((gint) VTE_ERASE_ASCII_DELETE);
    PRINT_CONSTANT((gint) VTE_ERASE_AUTO);
    PRINT_CONSTANT((gint) VTE_ERASE_DELETE_SEQUENCE);
    PRINT_CONSTANT((gint) VTE_ERASE_TTY);
    PRINT_CONSTANT((guint) VTE_FEATURE_FLAGS_MASK);
    PRINT_CONSTANT((guint) VTE_FEATURE_FLAG_BIDI);
    PRINT_CONSTANT((guint) VTE_FEATURE_FLAG_ICU);
    PRINT_CONSTANT((guint) VTE_FEATURE_FLAG_SIXEL);
    PRINT_CONSTANT((guint) VTE_FEATURE_FLAG_SYSTEMD);
    PRINT_CONSTANT((gint) VTE_FORMAT_HTML);
    PRINT_CONSTANT((gint) VTE_FORMAT_TEXT);
    PRINT_CONSTANT(VTE_MAJOR_VERSION);
    PRINT_CONSTANT(VTE_MICRO_VERSION);
    PRINT_CONSTANT(VTE_MINOR_VERSION);
    PRINT_CONSTANT((guint) VTE_PTY_DEFAULT);
    PRINT_CONSTANT((gint) VTE_PTY_ERROR_PTY98_FAILED);
    PRINT_CONSTANT((gint) VTE_PTY_ERROR_PTY_HELPER_FAILED);
    PRINT_CONSTANT((guint) VTE_PTY_NO_CTTY);
    PRINT_CONSTANT((guint) VTE_PTY_NO_FALLBACK);
    PRINT_CONSTANT((guint) VTE_PTY_NO_HELPER);
    PRINT_CONSTANT((guint) VTE_PTY_NO_LASTLOG);
    PRINT_CONSTANT((guint) VTE_PTY_NO_SESSION);
    PRINT_CONSTANT((guint) VTE_PTY_NO_UTMP);
    PRINT_CONSTANT((guint) VTE_PTY_NO_WTMP);
    PRINT_CONSTANT((gint) VTE_REGEX_ERROR_INCOMPATIBLE);
    PRINT_CONSTANT((gint) VTE_REGEX_ERROR_NOT_SUPPORTED);
    PRINT_CONSTANT(VTE_REGEX_FLAGS_DEFAULT);
    PRINT_CONSTANT(VTE_SPAWN_NO_PARENT_ENVV);
    PRINT_CONSTANT(VTE_SPAWN_NO_SYSTEMD_SCOPE);
    PRINT_CONSTANT(VTE_SPAWN_REQUIRE_SYSTEMD_SCOPE);
    PRINT_CONSTANT(VTE_TEST_FLAGS_ALL);
    PRINT_CONSTANT(VTE_TEST_FLAGS_NONE);
    PRINT_CONSTANT((gint) VTE_TEXT_BLINK_ALWAYS);
    PRINT_CONSTANT((gint) VTE_TEXT_BLINK_FOCUSED);
    PRINT_CONSTANT((gint) VTE_TEXT_BLINK_NEVER);
    PRINT_CONSTANT((gint) VTE_TEXT_BLINK_UNFOCUSED);
    PRINT_CONSTANT((gint) VTE_WRITE_DEFAULT);
    return 0;
}
