// Generated by gir (https://github.com/gtk-rs/gir @ e8f82cf6)
// from ../gir-files (@ 8e47c67)
// DO NOT EDIT

#include "manual.h"
#include <stdalign.h>
#include <stdio.h>

int main() {
    printf("%s;%zu;%zu\n", "VteCursorBlinkMode", sizeof(VteCursorBlinkMode), alignof(VteCursorBlinkMode));
    printf("%s;%zu;%zu\n", "VteCursorShape", sizeof(VteCursorShape), alignof(VteCursorShape));
    printf("%s;%zu;%zu\n", "VteEraseBinding", sizeof(VteEraseBinding), alignof(VteEraseBinding));
    printf("%s;%zu;%zu\n", "VteFeatureFlags", sizeof(VteFeatureFlags), alignof(VteFeatureFlags));
    printf("%s;%zu;%zu\n", "VteFormat", sizeof(VteFormat), alignof(VteFormat));
    printf("%s;%zu;%zu\n", "VtePtyError", sizeof(VtePtyError), alignof(VtePtyError));
    printf("%s;%zu;%zu\n", "VtePtyFlags", sizeof(VtePtyFlags), alignof(VtePtyFlags));
    printf("%s;%zu;%zu\n", "VteRegexError", sizeof(VteRegexError), alignof(VteRegexError));
    printf("%s;%zu;%zu\n", "VteTerminal", sizeof(VteTerminal), alignof(VteTerminal));
    printf("%s;%zu;%zu\n", "VteTerminalClass", sizeof(VteTerminalClass), alignof(VteTerminalClass));
    printf("%s;%zu;%zu\n", "VteTextBlinkMode", sizeof(VteTextBlinkMode), alignof(VteTextBlinkMode));
    printf("%s;%zu;%zu\n", "VteWriteFlags", sizeof(VteWriteFlags), alignof(VteWriteFlags));
    return 0;
}
